### PR TITLE
`mujoco-v5` initial commit

### PR DESCRIPTION
**Pull request by Kallinteris-Andreas**
cont from: https://github.com/Farama-Foundation/Gymnasium-Robotics/issues/91

# Description
Adds the `v5` version of the `mujoco` environments.

# Changelog
- `mujoco` minimum version is 2.3.3 now.
- added for support for fully-custom/third-party `mujoco` models with the usage of the `xml_file` argument (previously only a few changes could be made).
- added `default_camera_config` argument, a dictionary for setting the `mj_camera` properties, primarily useful for custom environments.
- added `env.observation_structure`, a dictionary indicating the composition of the observation space (e.g. `qpos`, `qvel`), useful for building tooling and wrappers for the MuJoCo environments.
- return `info` with `reset()`, previously an empty dictionary would be returned.
- added `frame_skip` argument.
 

## Ant
- fixed bug: `healthy_reward` being given on every step (even when the Ant is unhealthy), now it is only given when the Ant is healthy.  The `info` "reward_survive" is updated with this change.
- reward function now always includes `contact_cost`, previously it was only included when `use_contact_forces=True` (can be set to `0` with `contact_cost_weight=0`).
- excluded `worldbody`'s `cfrc_ext` from the observation space (since they are constantly 0, and therefore provide no useful information to the agent, should result is slightly faster training).
- added `main_body` argument.
- added `forward_reward_weight` argument.
- added `include_cfrc_ext_in_observation` argument.
- removed `use_contact_forces` argument (note: its functionality has been replaced with `include_cfrc_ext_in_observation` and `contact_cost_weight`).
- fix `info` "reward_ctrl" sometimes containing `contact_cost` instead of `ctrl_cost`.
- fixed `info` "x_position" & "y_position" giving `xpos` instead of `qpos` observations (`xpos` observations are behind 1 `mj_step()`).
- removed "forward_reward" from `info` (note: there still exits "reward_forward", which contains the same information).

## Half Cheetah
- re-added `xml_file` argument.
- renamed `info` "reward_run" → "reward_forward" (to be consistent with the other environments).

## Hopper
- changed model (new model does not require `coordinate='global'`, but has near identical behavior).
- fixed bug: `healthy_reward` being given on every step (even when the Hopper is unhealthy), now it is only given when the Ant is healthy.  The `info` "reward_survive" is updated with this change.
- re-added `xml_file` argument.
- added `info` "reward_forward", "reward_ctrl", "reward_survive", "z_distance_from_origin".

## Humanoid
- fixed bug: `healthy_reward` being given on every step (even when the Humanoid is unhealthy), now it is only given when the Ant is healthy.  The `info` "reward_survive" is updated with this change.
- re-added `contact_cost` (and the corresponding `contact_cost_weight` and `contact_cost_range` arguments).
- excluded `worldbody` `cinert` & `cvel` & `cfrc_ext` & `root`/`freejoint` `qfrc_actuator from the observation space (since they are constantly 0, and therefore provide no useful information to the agent, should result is slightly faster training).
- re-add `xml_file` argument.
- added `include_cinert_in_observation`, `include_cvel_in_observation`, `include_qfrc_actuator_in_observation`, `include_cfrc_ext_in_observation` arguments.
- fixed `info` "x_position" & "y_position" giving `xpos` instead of `qpos` observations (`xpos` observations are behind 1 `mj_step()`).
- added `info` "tendon_lenght" & "tendon_velocity".
- renamed `info`  "reward_alive" → "reward_survive" (to be consistent with the other environments).
- renamed `info` "reward_linvel" → "reward_forward" (to be consistent with the other environments).
- renamed `info` "reward_quadctrl" → "reward_ctrl" (to be consistent with the other environments).
- removed "forward_reward" from `info` (note: there still exits "reward_forward").

## Humanoid Standup
- excluded `worldbody` `cinert` & `cvel` & `cfrc_ext` & `root`/`freejoint` `qfrc_actuator from the observation space (since they are constantly 0, and therefore provide no useful information to the agent, should result is slightly faster training).
- added `xml_file`, `uph_cost_weight`, `ctrl_cost_weight`, `impact_cost_weight`, `impact_cost_range`, `reset_noise_scale`, `exclude_current_positions_from_observation`, `include_cinert_in_observation`, `include_cvel_in_observation`, `include_qfrc_actuator_in_observation`, `include_cfrc_ext_in_observation` arguments.
- added `info` "tendon_lenght" & "tendon_velocity".
- added `info`"x_position" & "y_position" & "z_distance_from_origin".

## InvertedDoublePendulum
- fixed bug: `healthy_reward` being given on every step (even when the Pendulum is unhealthy), now it is only given when the Ant is healthy.  The `info` "reward_survive" is updated with this change.
- removed `qfrc_constraint` ("constraint force") of the hinges from the observation space (since they are constantly 0, and therefore provide no useful information to the agent, should result is slightly faster training).
- added `xml_file`, `healthy_reward`, `reset_noise_scale` arguments.
- added `info` "reward_survive", "distance_penalty", "velocity_penalty".

## InvertedPendulum
- fixed bug: `healthy_reward` being given on every step (even when the Pendulum is unhealthy), now it is only given when the Ant is healthy.  The `info` "reward_survive" is updated with this change.
- added `xml_file`, `reset_noise_scale` arguments.
- added `info` "reward_survive".

## Pusher
- added `xml_file` argument.
- added `reward_near_weight`, `reward_dist_weight`, `reward_control_weight` arguments.
- fixed `info` "reward_ctrl" being not being multiplied by the reward weight.
- added `info`  "reward_near".

## Reacher
- remove "z - position_fingertip" from the observation space (since they are constantly 0, and therefore provide no useful information to the agent, should result is slightly faster training).
- added `xml_file` argument.
- added `reward_dist_weight`, `reward_control_weight` arguments.
- fixed `info` "reward_ctrl" being not being multiplied by the reward weight.

## Swimmer
- re-added `xml_file` argument.
- added `forward_reward_weight`, `ctrl_cost_weight`, `reset_noise_scale`, `exclude_current_positions_from_observation` arguments.
- replaced `info "reward_fwd"/ "forward_reward" → "reward_forward" ` (to be consistent with the other environments).

## Walker2D
- changed model (new model does not require `coordinate='global'`), now both feet have `friction==1.9`, previously the right foot had `friction==0.9` and left foot had `friction==1.9`.
- fixed bug: `healthy_reward` being given on every step (even when the Walker2D is unhealthy), now it is only given when the Ant is healthy.  The `info` "reward_survive" is updated with this change.
- re-added `xml_file` argument.
- added `info` "reward_forward", "reward_ctrl", "reward_survive",  "z_distance_from_origin".

## Type of change
add new revision of `MuJoCo` environments.

# Checklist:

- [X] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

# Benchmarks
- [X] benchmark similarly to https://github.com/openai/gym/pull/2595#issuecomment-1099152505 (`v3` → `v4`)
https://github.com/Kallinteris-Andreas/gymnasium-mujuco-v5-envs-validation

# issues fixed:
- [X] https://github.com/deepmind/mujoco/issues/833
- [x] https://github.com/Farama-Foundation/Gymnasium/issues/539
- [x] https://github.com/Farama-Foundation/Gymnasium/issues/526
- [x] https://github.com/Farama-Foundation/Gymnasium/issues/521
- [x] https://github.com/Farama-Foundation/Gymnasium/issues/504
- [x] https://github.com/Farama-Foundation/Gymnasium/issues/500
- [x] https://github.com/Farama-Foundation/Gymnasium/issues/477
- [x] https://github.com/Farama-Foundation/Gymnasium/issues/473
- [x] https://github.com/Farama-Foundation/Gymnasium/issues/228
- [x] https://github.com/Farama-Foundation/Gymnasium/issues/220
- [x] https://github.com/Farama-Foundation/Gymnasium/issues/214
- [x] https://github.com/Farama-Foundation/Gymnasium/issues/204

# TODO
- [ ] Verify that docs are being built
- [ ] Update "Version History"
- [ ] Blog anouncement ???
- [ ] Minary Dataset generation ???
## Finished environments
- [x] Ant
- [x] Half Cheetah
- [X] Hopper
- [X] Humanoid
- [x] Humanoid Standup
- [x] Inverted Double Pendulum 
- [x] Inverted Pendulum
- [x] Reacher
- [x] Swimmer
- [x] Pusher
- [X] Walker2D

# Cutting room floor (not included in the `v5` release)
- add option for observing tendons in `Humanoid`s
- update kinematics of `Ant` & `Humanoid` after step
- add `ManySegmentSwimmer` & `CoupledHalfCheetah` environments
- adding `reset_noise_scale` to `Pusher` & `Reacher`

# Credits
Lead Developer: Kallinteris Andreas
Debugging assistance & setting specification/requirements: Rodrigo, Mark Towers
Technical Advisor: saran-t (helped with the creation of the new `Hopper` and `Walker2D` models)

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
@Kallinteris-Andreas Thanks for all of this hard work, we are planning on having a gymnasium v0.28.2 and v0.29 in the next few weeks. If there are any changes you want to make in gymnasium, could you do them soon, thanks

**Comment by Kallinteris-Andreas** [comment]
@pseudo-rnd-thoughts
1. I do not need anything in gymnasium.
2. The CI will be fixed once `mujoco` envs get moved to this repo
3. I am still evaluating the impact of https://github.com/Farama-Foundation/Gymnasium/issues/526, after that it should be ready for review.

**Comment by Kallinteris-Andreas** [comment]
Yeah, The `brax` simulator is not at the required feature parity to replace the `mujoco` envs in gymnasium.

After validation, I can move the PR to the gymnasium repo, it is no problem.

**Comment by Kallinteris-Andreas** [comment]
@pseudo-rnd-thoughts & @rodrigodelazcano 
Thought development in the past 4 months a lot of changes has been accumulated.
Can you do a review of the change list (just the changelog, not the code), to make sure that all the changes are desired and properly explained?


Note: the changelog here will be used in the `Version History` part of the documentation
Note: I will create a PR in gymnasium, in the next few days.

**Comment by Kallinteris-Andreas** [comment]
@pseudo-rnd-thoughts thanks, I have made a bunch of improvements.

Can you do a second pass of the change list, to make sure that all the changes are desired.

**Comment by pseudo-rnd-thoughts** [comment]
> Can you do a second pass of the change list, to make sure that all the changes are desired.

Without more detail, I can't understand all of the changes, could you do a documentation update

**Comment by Kallinteris-Andreas** [comment]
All the changes are in the docstings of the environments

**Pull request closed without merging**
