### PR TITLE
[MaMuJoCo] add observation types to the documention 

### PR DESCRIPTION
**Pull request by Kallinteris-Andreas**
# Description

Currently, there is no explanation in the DOCs of the default and supported observation types for `MaMuJoCo`
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] DOC update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Kallinteris-Andreas** [comment]
this repo is not affected by that problem

**Comment by rodrigodelazcano** [comment]
Are you sure? The build error from the `pytest` shows the following:

image

**Comment by Kallinteris-Andreas** [comment]
@rodrigodelazcano from what I can tell only `Gymansium/MuJoCo` is affected

**Comment by Kallinteris-Andreas** [comment]
@rodrigodelazcano re-run CI

**Pull request merged**
