### PR TITLE
update observation space docstring for `fetch` `pick_and_place` `push` `slide` environments

### PR DESCRIPTION
**Pull request by SethPate**
# Description

The docstring for the observations space in the Fetch Push, Slide, PickAndPlace tasks has a typo. I didn't find a similar problem in Reach. This is only a change to the docstring.

Fixes # (issue)

## Type of change

- [x] This change requires a documentation update

### Screenshots

n/a

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Kallinteris-Andreas** [comment]
1) can you run pre-commit?
2) can you point to the code that corresponds to the changed documentation (with a perma-link)
Thanks

**Comment by SethPate** [comment]
Here's the relevant code: 
https://github.com/Farama-Foundation/Gymnasium-Robotics/blob/f2754e19011a6ef329a40efc92dfa4bad81a22d3/gymnasium_robotics/envs/fetch/fetch_env.py#L205C1-L205C51

I'm seeing the same failure on pre-commit, not sure what would cause it to break.

**Review by Kallinteris-Andreas — APPROVED** [review]
Thanks, for the fixes!!!

**Comment by Kallinteris-Andreas** [comment]
I will merge as soon as I fix the CI situation

**Comment by Kallinteris-Andreas** [comment]
The perma-link provided in a previous post was for the old`mujoco-py` based version for context new version: 
https://github.com/Farama-Foundation/Gymnasium-Robotics/blob/f2754e19011a6ef329a40efc92dfa4bad81a22d3/gymnasium_robotics/envs/fetch/fetch_env.py#L314-L338

**Pull request merged**
